"""Stream type classes for tap-salesloft."""

from .account_stages import AccountStagesStream
from .account_team_member_roles import AccountTeamMemberRolesStream
from .account_tiers import AccountTiersStream
from .account_types import AccountTypesStream
from .accounts import AccountsStream
from .actions import ActionsStream
from .activity_histories import ActivityHistoriesStream
from .audit_reports import AuditReportsStream
from .cadence_memberships import CadenceMembershipsStream
from .cadences import CadencesStream
from .calendar_events import CalendarEventsStream
from .call_data_records import CallDataRecordsStream
from .call_dispositions import CallDispositionsStream
from .call_instructions import CallInstructionsStream
from .call_sentiments import CallSentimentsStream
from .calls import CallsStream
from .crm_account_team_members import CrmAccountTeamMembersStream
from .crm_activites import CrmActivitiesStream
from .crm_activity_fields import CrmActivityFieldsStream
from .crm_team_members_with_roles import CrmTeamMembersWithRolesStream
from .crm_users import CrmUsersStream
from .custom_fields import CustomFieldsStream
from .custom_roles import CustomRolesStream
from .email_template_attachments import EmailTemplateAttachmentsStream
from .email_templates import EmailTemplatesStream
from .emails import EmailsStream
from .external_configurations import ExternalConfigurationsStream
from .external_mappings import ExternalMappingsStream
from .groups import GroupsStream
from .imports import ImportsStream
from .meetings import MeetingsStream
from .notes import NotesStream
from .opportunities import OpportunitiesStream
from .opportunity_people import OpportunityPeopleStream
from .opportunity_stages import OpportunityStagesStream
from .pending_emails import PendingEmailsStream
from .people import PeopleStream
from .person_stages import PersonStagesStream
from .phone_number_assignments import PhoneNumberAssignmentsStream
from .registrations_plays import RegistrationsPlaysStream
from .saved_list_views import SavedListViewsStream
from .signals_registrations import SignalsRegistrationsStream
from .steps import StepsStream
from .successes import SuccessesStream
from .tags import TagsStream
from .tasks import TasksStream
from .team_template_attachments import TeamTemplateAttachmentsStream
from .team_templates import TeamTemplatesStream
from .transcriptions import TranscriptionsStream
from .users import UsersStream
from .webhook_subscriptions import WebhookSubscriptionsStream
